import { jsPDF } from 'jspdf';
import { Invoice, BusinessProfile, Customer } from '../types.ts';
import { format } from 'date-fns';

export const generateInvoicePDF = async (invoice: Invoice, profile: BusinessProfile | null, customer: Customer | undefined) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  // Colors
  const primary = (invoice as any).accentColor || '#FF4444';
  const black = '#0A0A0A';
  const gray = '#8E9299';

  // Branding
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(black);
  doc.text(profile?.name || 'BUSINESS NAME', 20, 25);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(gray);
  doc.text(profile?.address || '', 20, 32);
  doc.text(profile?.email || '', 20, 36);
  if (profile?.taxId) doc.text(`Tax ID: ${profile.taxId}`, 20, 40);

  // Invoice Meta
  doc.setFontSize(30);
  doc.setTextColor(primary);
  doc.text('INVOICE', 140, 25);
  
  doc.setFontSize(10);
  doc.setTextColor(black);
  doc.setFont('helvetica', 'bold');
  doc.text(`NO: #${invoice.number}`, 140, 32);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(gray);
  doc.text(`Date: ${format(invoice.date, 'MMM dd, yyyy')}`, 140, 38);
  doc.text(`Due: ${format(invoice.dueDate, 'MMM dd, yyyy')}`, 140, 42);

  const dividerY = 55;
  doc.setDrawColor(240, 240, 240);
  doc.line(20, dividerY, 190, dividerY);

  // Billing Info
  doc.setFontSize(9);
  doc.setTextColor(gray);
  doc.setFont('helvetica', 'bold');
  doc.text('BILLED TO', 20, 70);
  
  doc.setFontSize(12);
  doc.setTextColor(black);
  doc.text(customer?.name || 'Client Name', 20, 78);
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(gray);
  doc.text(customer?.address || '', 20, 84);
  doc.text(customer?.email || '', 20, 88);

  // Table
  const tableTop = 110;
  doc.setFillColor(black);
  doc.rect(20, tableTop, 170, 10, 'F');
  
  doc.setFontSize(8);
  doc.setTextColor('#FFFFFF');
  doc.setFont('helvetica', 'bold');
  doc.text('DESCRIPTION', 25, tableTop + 6.5);
  doc.text('QTY', 110, tableTop + 6.5);
  doc.text('PRICE', 135, tableTop + 6.5);
  doc.text('TAX %', 155, tableTop + 6.5);
  doc.text('AMOUNT', 175, tableTop + 6.5);

  let currentY = tableTop + 18;
  doc.setTextColor(black);
  doc.setFont('helvetica', 'normal');

  invoice.items.forEach((item, index) => {
    doc.text(item.description, 25, currentY);
    doc.text(item.quantity.toString(), 110, currentY);
    doc.text(`$${item.price.toFixed(2)}`, 135, currentY);
    doc.text(`${item.taxRate}%`, 155, currentY);
    doc.text(`$${(item.quantity * item.price).toFixed(2)}`, 175, currentY);
    
    currentY += 10;
    doc.setDrawColor(245, 245, 245);
    doc.line(20, currentY - 6, 190, currentY - 6);
  });

  // Totals
  const totalY = Math.max(currentY + 10, 220);
  doc.setFontSize(9);
  doc.setTextColor(gray);
  doc.text('SUBTOTAL', 140, totalY);
  doc.text('TAXES', 140, totalY + 6);
  
  doc.setTextColor(black);
  doc.setFont('helvetica', 'bold');
  doc.text(`$${invoice.subtotal.toFixed(2)}`, 175, totalY);
  doc.text(`$${invoice.taxTotal.toFixed(2)}`, 175, totalY + 6);
  
  doc.setDrawColor(black);
  doc.line(135, totalY + 10, 190, totalY + 10);
  
  doc.setFontSize(14);
  doc.text('TOTAL', 140, totalY + 18);
  doc.setTextColor(primary);
  doc.text(`$${invoice.total.toFixed(2)}`, 175, totalY + 18);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(gray);
  doc.setFont('helvetica', 'italic');
  doc.text(`Note: ${invoice.notes || 'No special notes.'}`, 20, 270);
  doc.text('Generated by NovaBill - High Performance Invoicing', 105, 285, { align: 'center' });

  // Save the PDF
  doc.save(`Invoice_${invoice.number}.pdf`);
};
